name: Update Stats

on:
  schedule:
    - cron: '23 0 * * *' # Chạy vào 00:00 mỗi ngày (UTC)
  workflow_dispatch: # Cho phép bấm nút chạy tay để test

jobs:
  update-tiktok:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền ghi để commit file json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_stats.py

      - name: Commit and Push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add stats.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update stats" && git push)
